npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-yaml-manifest.cjs
    spec: bundles/@yarnpkg/plugin-yaml-manifest.js

yarnPath: .yarn/releases/yarn-3.1.1.cjs
