name: yarn-plugin-yaml-manifest
version: 0.0.1
description: Yarn Berry plugin to use YAML manifest file.
main: src/index.ts
author: Lyle Underwood <lyleunderwood@gmail.com>
license: MIT

scripts:
  # outputs the plugin bundle to ./bundles
  build: builder build plugin
  ts:check: tsc --noEmit
  jest: jest ./test/index.jest.ts
  test: docker build -t yarn-plugin-yaml-manifest-test . && docker run -it -v ${PWD}/test:/app/test -v ${PWD}/.git:/app/.git -v ${PWD}/bundles:/app/bundles yarn-plugin-yaml-manifest-test
  import: yarn plugin import ./bundles/@yarnpkg/plugin-yaml-manifest.js

dependencies:
  # specifies JavaScript object patch format and implements diffing
  rfc6902: ^5.0.0
  # for parsing YAML
  yaml: ^1.10.2
  # for patching YAML (accepts RFC6902 patch operations)
  yaml-diff-patch: ^1.1.0

  # yarn plugin stuff
  clipanion: ^3.2.0-rc.4
  typanion: ^3.7.1
  "@yarnpkg/core": ^3.2.0-rc.8
  "@yarnpkg/fslib": "^2.6.1-rc.3"
  "globby": 11.0.4

devDependencies:
  # build
  "@yarnpkg/builder": ^3.1.0

  # linting
  eslint: ^8.5.0
  eslint-config-prettier: ^8.3.0
  eslint-plugin-prettier: ^4.0.0
  prettier: ^2.5.1

  # typescript
  typescript: ^4.5.4
  # it's unclear to me whether these are still necessary
  "@typescript-eslint/eslint-plugin": ^5.8.0
  "@typescript-eslint/parser": ^5.8.0

  # types
  "@types/node": ^17.0.2

  # testing
  jest: ^27.4.5
  ts-node: ^10.4.0
  "@jest/types": ^27.4.2
  jest-config: ^27.4.5
  "@types/jest": ^27.0.3
  "@babel/core": ^7.16.5
  "@babel/preset-env": ^7.16.5
  babel-jest: ^27.4.5
  "@babel/preset-typescript": ^7.16.5
  source-map-support: ^0.5.21

packageManager: yarn@3.1.1
